name: Release to npm

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build:bionic

      - name: Run tests
        run: npm run test:bionic

      - name: Publish to npm
        run: npm run publish:bionic
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}